[2024-01-04T12:18:59.519+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T07:20:00+00:00 [queued]>
[2024-01-04T12:18:59.541+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T07:20:00+00:00 [queued]>
[2024-01-04T12:18:59.542+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T12:18:59.601+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_orders> on 2024-01-04 07:20:00+00:00
[2024-01-04T12:18:59.608+0000] {standard_task_runner.py:57} INFO - Started process 506 to run task
[2024-01-04T12:18:59.615+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_orders', 'scheduled__2024-01-04T07:20:00+00:00', '--job-id', '617', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmp6wfortlg']
[2024-01-04T12:18:59.617+0000] {standard_task_runner.py:85} INFO - Job 617: Subtask insert_into_orders
[2024-01-04T12:18:59.710+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T07:20:00+00:00 [running]> on host 399e7321ffbc
[2024-01-04T12:18:59.899+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T07:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T07:20:00+00:00'
[2024-01-04T12:18:59.901+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Orders (order_id, customer_id, order_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (order_id) DO NOTHING;
[2024-01-04T12:18:59.921+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:18:59.944+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:19:00.092+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Orders (order_id, customer_id, order_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (order_id) DO NOTHING;, parameters: None
[2024-01-04T12:19:00.104+0000] {sql.py:427} INFO - Rows affected: 0
[2024-01-04T12:19:00.134+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_orders, execution_date=20240104T072000, start_date=20240104T121859, end_date=20240104T121900
[2024-01-04T12:19:00.233+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-04T12:19:00.290+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
