[2024-01-04T12:19:33.802+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T08:08:00+00:00 [queued]>
[2024-01-04T12:19:33.830+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T08:08:00+00:00 [queued]>
[2024-01-04T12:19:33.831+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T12:19:33.875+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_orders> on 2024-01-04 08:08:00+00:00
[2024-01-04T12:19:33.893+0000] {standard_task_runner.py:57} INFO - Started process 608 to run task
[2024-01-04T12:19:33.910+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_orders', 'scheduled__2024-01-04T08:08:00+00:00', '--job-id', '664', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmpkghmra7f']
[2024-01-04T12:19:33.915+0000] {standard_task_runner.py:85} INFO - Job 664: Subtask insert_into_orders
[2024-01-04T12:19:34.102+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T08:08:00+00:00 [running]> on host 399e7321ffbc
[2024-01-04T12:19:34.417+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T08:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T08:08:00+00:00'
[2024-01-04T12:19:34.420+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Orders (order_id, customer_id, order_date)
    VALUES
        (1, 1, NOW()),
        (2, 2, NOW())
    ON CONFLICT (order_id) DO NOTHING;
[2024-01-04T12:19:34.458+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:19:34.487+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:19:34.612+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Orders (order_id, customer_id, order_date)
    VALUES
        (1, 1, NOW()),
        (2, 2, NOW())
    ON CONFLICT (order_id) DO NOTHING;, parameters: None
[2024-01-04T12:19:34.619+0000] {sql.py:427} INFO - Rows affected: 0
[2024-01-04T12:19:34.651+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_orders, execution_date=20240104T080800, start_date=20240104T121933, end_date=20240104T121934
[2024-01-04T12:19:34.730+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-04T12:19:34.815+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
