[2024-01-04T11:19:20.905+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task-3.create_postgres_table scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-01-04T11:19:20.925+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task-3.create_postgres_table scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-01-04T11:19:20.926+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T11:19:20.960+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-01-03 00:00:00+00:00
[2024-01-04T11:19:20.973+0000] {standard_task_runner.py:57} INFO - Started process 2666 to run task
[2024-01-04T11:19:20.980+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task-3', 'create_postgres_table', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmpsfntmdvm']
[2024-01-04T11:19:20.983+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask create_postgres_table
[2024-01-04T11:19:21.087+0000] {task_command.py:416} INFO - Running <TaskInstance: Task-3.create_postgres_table scheduled__2024-01-03T00:00:00+00:00 [running]> on host 89e7ff4d9ff4
[2024-01-04T11:19:21.307+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Task-3' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-01-04T11:19:21.309+0000] {sql.py:274} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS your_table_name (
                column1 datatype1,
                column2 datatype2,
                -- add more columns as needed
            );
        
[2024-01-04T11:19:21.328+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T11:19:21.360+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T11:19:21.442+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "***"

[2024-01-04T11:19:21.459+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Task-3, task_id=create_postgres_table, execution_date=20240103T000000, start_date=20240104T111920, end_date=20240104T111921
[2024-01-04T11:19:21.477+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 83 for task create_postgres_table (connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "***"
; 2666)
[2024-01-04T11:19:21.516+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-04T11:19:21.543+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
