[2024-01-04T12:19:24.017+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T07:50:00+00:00 [queued]>
[2024-01-04T12:19:24.070+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T07:50:00+00:00 [queued]>
[2024-01-04T12:19:24.083+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T12:19:24.313+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_orders> on 2024-01-04 07:50:00+00:00
[2024-01-04T12:19:24.331+0000] {standard_task_runner.py:57} INFO - Started process 579 to run task
[2024-01-04T12:19:24.351+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_orders', 'scheduled__2024-01-04T07:50:00+00:00', '--job-id', '648', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmp0kdpwdqq']
[2024-01-04T12:19:24.358+0000] {standard_task_runner.py:85} INFO - Job 648: Subtask insert_into_orders
[2024-01-04T12:19:24.646+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T07:50:00+00:00 [running]> on host 399e7321ffbc
[2024-01-04T12:19:25.119+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T07:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T07:50:00+00:00'
[2024-01-04T12:19:25.122+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Orders (order_id, customer_id, order_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (order_id) DO NOTHING;
[2024-01-04T12:19:25.166+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:19:25.239+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:19:25.447+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Orders (order_id, customer_id, order_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (order_id) DO NOTHING;, parameters: None
[2024-01-04T12:19:25.472+0000] {sql.py:427} INFO - Rows affected: 0
[2024-01-04T12:19:25.503+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_orders, execution_date=20240104T075000, start_date=20240104T121924, end_date=20240104T121925
[2024-01-04T12:19:25.620+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-04T12:19:25.919+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
