[2024-01-05T06:31:24.365+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task5.check_cache_task scheduled__2024-01-04T21:04:00+00:00 [queued]>
[2024-01-05T06:31:24.523+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task5.check_cache_task scheduled__2024-01-04T21:04:00+00:00 [queued]>
[2024-01-05T06:31:24.526+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-05T06:31:24.854+0000] {taskinstance.py:1382} INFO - Executing <Task(SqlSensor): check_cache_task> on 2024-01-04 21:04:00+00:00
[2024-01-05T06:31:24.881+0000] {standard_task_runner.py:57} INFO - Started process 1422 to run task
[2024-01-05T06:31:24.943+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task5', 'check_cache_task', 'scheduled__2024-01-04T21:04:00+00:00', '--job-id', '2831', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-4.py', '--cfg-path', '/tmp/tmp82f2itmh']
[2024-01-05T06:31:25.007+0000] {standard_task_runner.py:85} INFO - Job 2831: Subtask check_cache_task
[2024-01-05T06:31:25.461+0000] {task_command.py:416} INFO - Running <TaskInstance: Task5.check_cache_task scheduled__2024-01-04T21:04:00+00:00 [running]> on host 73272df13e14
[2024-01-05T06:31:26.738+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task5' AIRFLOW_CTX_TASK_ID='check_cache_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T21:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T21:04:00+00:00'
[2024-01-05T06:31:26.883+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-05T06:31:26.900+0000] {sql.py:95} INFO - Poking: SELECT COUNT(*) FROM Purchase_details_cache WHERE created_time > NOW() - INTERVAL '4 minutes'; (with parameters None)
[2024-01-05T06:31:26.937+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-05T06:31:27.231+0000] {sql.py:418} INFO - Running statement: SELECT COUNT(*) FROM Purchase_details_cache WHERE created_time > NOW() - INTERVAL '4 minutes';, parameters: None
[2024-01-05T06:31:27.276+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/sensors/sql.py", line 96, in poke
    records = hook.get_records(self.sql, self.parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 255, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "purchase_details_cache" does not exist
LINE 1: SELECT COUNT(*) FROM Purchase_details_cache WHERE created_ti...
                             ^

[2024-01-05T06:31:27.494+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Task5, task_id=check_cache_task, execution_date=20240104T210400, start_date=20240105T063124, end_date=20240105T063127
[2024-01-05T06:31:28.186+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2831 for task check_cache_task (relation "purchase_details_cache" does not exist
LINE 1: SELECT COUNT(*) FROM Purchase_details_cache WHERE created_ti...
                             ^
; 1422)
[2024-01-05T06:31:28.334+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-05T06:31:28.711+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
