[2024-01-04T12:10:36.835+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T03:58:00+00:00 [queued]>
[2024-01-04T12:10:36.881+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T03:58:00+00:00 [queued]>
[2024-01-04T12:10:36.887+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T12:10:36.955+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_product_returns> on 2024-01-04 03:58:00+00:00
[2024-01-04T12:10:36.969+0000] {standard_task_runner.py:57} INFO - Started process 884 to run task
[2024-01-04T12:10:36.986+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_product_returns', 'scheduled__2024-01-04T03:58:00+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmp5pw1co_h']
[2024-01-04T12:10:36.991+0000] {standard_task_runner.py:85} INFO - Job 400: Subtask insert_into_product_returns
[2024-01-04T12:10:37.274+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T03:58:00+00:00 [running]> on host 399e7321ffbc
[2024-01-04T12:10:37.574+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_product_returns' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T03:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T03:58:00+00:00'
[2024-01-04T12:10:37.576+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    
[2024-01-04T12:10:37.596+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:10:37.622+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:10:37.740+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    , parameters: None
[2024-01-04T12:10:37.749+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "product_returns_pkey"
DETAIL:  Key (return_id)=(1) already exists.

[2024-01-04T12:10:37.780+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Task4, task_id=insert_into_product_returns, execution_date=20240104T035800, start_date=20240104T121036, end_date=20240104T121037
[2024-01-04T12:10:37.823+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 400 for task insert_into_product_returns (duplicate key value violates unique constraint "product_returns_pkey"
DETAIL:  Key (return_id)=(1) already exists.
; 884)
[2024-01-04T12:10:37.864+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-04T12:10:38.240+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
