[2024-01-04T12:40:02.674+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T12:38:00+00:00 [queued]>
[2024-01-04T12:40:02.704+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T12:38:00+00:00 [queued]>
[2024-01-04T12:40:02.705+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T12:40:02.768+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_orders> on 2024-01-04 12:38:00+00:00
[2024-01-04T12:40:02.788+0000] {standard_task_runner.py:57} INFO - Started process 1389 to run task
[2024-01-04T12:40:02.802+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_orders', 'scheduled__2024-01-04T12:38:00+00:00', '--job-id', '937', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmpglt199r4']
[2024-01-04T12:40:02.806+0000] {standard_task_runner.py:85} INFO - Job 937: Subtask insert_into_orders
[2024-01-04T12:40:02.995+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T12:38:00+00:00 [running]> on host 399e7321ffbc
[2024-01-04T12:40:03.254+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T12:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T12:38:00+00:00'
[2024-01-04T12:40:03.256+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Orders (order_id, customer_id, order_date)
    VALUES
        (1, 1, NOW()),
        (2, 2, NOW())
    ON CONFLICT (order_id) DO NOTHING;
[2024-01-04T12:40:03.288+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:40:03.334+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:40:03.445+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Orders (order_id, customer_id, order_date)
    VALUES
        (1, 1, NOW()),
        (2, 2, NOW())
    ON CONFLICT (order_id) DO NOTHING;, parameters: None
[2024-01-04T12:40:03.451+0000] {sql.py:427} INFO - Rows affected: 0
[2024-01-04T12:40:03.477+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_orders, execution_date=20240104T123800, start_date=20240104T124002, end_date=20240104T124003
[2024-01-04T12:40:03.533+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-04T12:40:03.589+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
